### ISSUE TITLE
Default Zoom level is too small

### ISSUE THREAD

**Issue by snwh** [stuartlangridge/ColourPicker#10]
It's hard to select things of a single-pixel's width at the level of zoom in the cursor. It appears to be currently x2 zoom, I think x4 (or more) zoom would be more effective.

**Comment by stuartlangridge** [comment]
The mouse wheel increases and decreases the zoom level. Suggestions for how to make this more obvious are gratefully accepted :)

**Comment by snwh** [comment]
Is possible to keep the circle "window" the same size when one zooms?

**Comment by stuartlangridge** [comment]
Hm. Probably. I'll experiment and see if things are still understandable when that's done.

**Comment by snwh** [comment]
If you zoom in with a microscope, the eyepiece doesn't increase in diameter ;)

What are the increments for the zoom anyway?

**Comment by stuartlangridge** [comment]
I have jacked up the default zoom level (in the next release). However, after some experimentation, I think I prefer making the eyepiece increase in diameter as well as the zoom level of the stuff inside it increasing; it helps alleviate problems with the eyepiece being too small (if people think that), and once the zoom level is up above about 3x it's really hard to see the context around where you're actually mousing over and therefore you can't tell what you're looking at -- microscopes actually have that problem, which is what I'm trying to avoid :) So I'm going to close this for now, but I'm happy to hear argument about why I'm wrong and the eyepiece should stay the same size :)
