### ISSUE TITLE
Crashed on clicking Pick icon

### ISSUE THREAD

**Issue by Foggalong** [stuartlangridge/ColourPicker#17]
The app installs fine, but crashes whenever I click the pick icon in the interface. This is the terminal output, but this all happens before the button is clicked - there's no output after that point.

![screenshot_2016-05-29_13-33-34](https://cloud.githubusercontent.com/assets/5920259/15633331/1416b8f4-25a2-11e6-988b-8902c0131950.png)

**Comment by stuartlangridge** [comment]
I think I've broken something. Working on it.

**Comment by stuartlangridge** [comment]
god, how embarrassing. Fixed in https://github.com/stuartlangridge/ColourPicker/commit/19d5385187ab6e21142074ca72677779943df2ce
