### ISSUE TITLE
Takes Over Mouse

### ISSUE THREAD

**Issue by Foggalong** [stuartlangridge/ColourPicker#18]
Following on from #17, sometimes instead of just crashing the magnified circle picker appears and replaces the mouse, but then doesn't go away. The mouse isn't frozen (the circle can still be moved around) but the image within the circle doesn't change and it's impossible to click anything.

I've tried to take a screenshot of this but it doesn't work. The only way to gain control again is to go over to a tty and kill the program from there.

**Comment by stuartlangridge** [comment]
I think this should be fixed by the same commit as #17, https://github.com/stuartlangridge/ColourPicker/commit/19d5385187ab6e21142074ca72677779943df2ce but please let me know if not. (Package 1.4 building in Launchpad now.)

**Comment by Foggalong** [comment]
All working fine with 1.4. Thanks for the quick fix :+1:
![screenshot_2016-05-29_17-52-16](https://cloud.githubusercontent.com/assets/5920259/15634842/25d26394-25c6-11e6-893c-78797c816fa0.png)

**Comment by stuartlangridge** [comment]
I left a debug print in there, which I'll remove, but I'm not issuing a new version just for that so it'll go away when a 1.5 arrives ;)
