### ISSUE TITLE
Looks weird on dark theme

### ISSUE THREAD

**Issue by HEXcube** [stuartlangridge/ColourPicker#2]
There's this white text on white background problem when GTK3's global dark theme mode is enabled. It's not just the text problem though: that whitish area looks out of place on dark mode. See:

On **Ubuntu 14.04LTS** with _Numix_ theme:
![Pick with Dark theme on Ubuntu 14.04LTS](https://cloud.githubusercontent.com/assets/3755396/15477891/da931404-2134-11e6-9672-f53c53a1b20e.png)

I tested the latest Pick from [the PPA](https://code.launchpad.net/~sil/+archive/ubuntu/pick/) on both Ubuntu 16.04LTS and 14.04LTS and this issue exists on both.

On **Ubuntu GNOME 16.04LTS** with _Adapta_ theme:
![Dark theme problem of Pick](https://cloud.githubusercontent.com/assets/3755396/15510909/08e15588-21f7-11e6-854b-d4c1502e16ff.png)

**Comment by stuartlangridge** [comment]
Huh. You are correct. How do I enable such a dark theme on Ubuntu 14.04 to test it? I tested in High Contrast, but I didn't know about a dark theme.

**Comment by HEXcube** [comment]
Well, there are many ways to enable it. But the easiest one'd be to install **GNOME Tweak Tool** and use the _'Global Dark Theme'_ setting:

![Global Dark Theme](https://cloud.githubusercontent.com/assets/3755396/14120453/8677ad02-f610-11e5-911c-d72cc81c7174.png)

If you don't wanna install an extra app, just create this file `~/.config/gtk-3.0/settings.ini` and add this content to it:

```
[Settings]
gtk-application-prefer-dark-theme=1
```

Oh, and one more thing: Ubuntu's default theme Ambiance doesn't support dark mode unfortunately. :worried: So, you'll need to try this on some other themes like _Adwaita_ (GNOME's default theme), _Numix_, _Adapta_, _Paper_ etc. :relaxed:

**Comment by HEXcube** [comment]
Thanx for fixing this issue @stuartlangridge ! :relaxed: Pick looks much better on dark theme now. See:

![Dark theme fixed for Pick](https://cloud.githubusercontent.com/assets/3755396/15544827/c16cb492-22b7-11e6-8a89-4a1a2635c673.png)
