### ISSUE TITLE
have to unminimize the window and hover mouse over it before cursor changes

### ISSUE THREAD

**Issue by unhammer** [stuartlangridge/ColourPicker#21]
with 1.5-0~201606011144~ubuntu16.04.1 under Xfce, I have to unminimize the window and hover the mouse over it before the cursor changes as it should.

[recordmydesktop ogv](https://github.com/stuartlangridge/ColourPicker/files/298399/out.ogv.zip)

**Comment by stuartlangridge** [comment]
Thank you. This is obviously a bug, but it doesn't happen on systems I have access to. Maybe I can test on a vm; can you say which OS you're using?

**Comment by unhammer** [comment]
oh thought the package name indicated it, but guess that's used for many OS-es … I'm on Xubuntu 16.04

**Comment by nshiell** [comment]
Hi, I just tried running this on Kubuntu 16.04
KDE Plasma Version 5.5.5 (I know that being a KDE DE it's a little different from GNOME, so not sure how interested you are on thinking about this)
I have a simmilar issue to what @unhammer described, when the window minimizes the fish eye doesn't work, however wen you unminimize the window it's fine.

I played around by commenting out: self.w.iconify() and then it worked ok (however no window minimize happend). Did you fix the bug in Xfce? I wounder if Xfce is having the same issue as I have just seen in KDE?

**Comment by lorem--ipsum** [comment]
Same problem here, running Xubuntu 16.04. I have to unminimize the app and hover it before the magnifying glass shows up. A shame, really, because aside from that, Pick is really useful.

**Comment by Gruntfuggly** [comment]
Same problem. Makes it unusable as I need to grab loads of colours. 8-(

**Comment by stuartlangridge** [comment]
Unfortunately I can't replicate this; it doesn't happen to me, and I don't understand why...

**Comment by Gruntfuggly** [comment]
If it helps, I'm running Ubuntu 16.04, with the Metacity window manager.

Perhaps you could add an option not to minimize the application when starting the pick?

**Comment by stuartlangridge** [comment]
I believe this bug should now be fixed, because we no longer minimise the Pick window when picking.
