### ISSUE TITLE
aur package

### ISSUE THREAD

**Issue by langston-barrett** [stuartlangridge/ColourPicker#23]

**Comment by stuartlangridge** [comment]
Erm, is this a bug asking me to create such a package? I don't know anything about AUR; I thought that the way it worked was that an Arch person created such a thing?

**Comment by langston-barrett** [comment]
It's not a bug, but a public feature request. If I have time, I'll make one, but if anyone else wants to that'd be nice too :-)

**Comment by stuartlangridge** [comment]
Fair play! I'll leave this open, then; anyone is welcome to pick up on it.

**Comment by MightySCollins** [comment]
Looks like there is one now: https://aur.archlinux.org/packages/pick-colour-picker/. It's PKGBUILD just seems to be wrong :(

**Comment by jvault** [comment]
Try to build with the sil-build.sh script but throw an error.
AUR PKGBUILD is invalid, i am update it but something always goes wrong.
Flatpak never work.
Even pie to copy and run the binaries manually, but:

"The 'pick-colour-picker==1.0' distribution was not found and is required by the application".

I give up. There is simply no way to use that in Arch.

**Comment by rmdwirizki** [comment]
Modify the PKGBUILD with this code works for me : 
(this is taken from anglebeta's comment on https://aur.archlinux.org/packages/pick-colour-picker)

```
pkgname=pick-colour-picker
pkgver=1.5
pkgrel=0
pkgdesc="Pick. A colour picker that remembers where you picked colours from"
arch=('any')
url="http://kryogenix.org/code/pick/"
license=('custom')
depends=('python2-pip')
source=("${pkgname}_${pkgver}-0-201702011054-ubuntu17.10.1_all.deb::https://code.launchpad.net/~sil/+archive/ubuntu/pick/+files/${pkgname}_${pkgver}-0~201702011054~ubuntu17.10.1_all.deb")
md5sums=('6debb5d29903792366725131b6d082c7')
prepare() {
bsdtar -xJf data.tar.xz

}
package() {
cp --preserve=mode -r usr "${pkgdir}"
find "${pkgdir}" -type f -name 'pick-colour-picker' -exec sed -i "s/python/python2/g" {} \;
find "${pkgdir}" -depth -type d -name "dist-packages" -execdir mv {} "site-packages" \;
find "${pkgdir}" -type d -exec chmod 755 {} \;
install -dm755 "${pkgdir}"/usr/share/licenses/$pkgname
mv "${pkgdir}"/usr/share/licenses/$pkgname .
}
```
And don't forget to install python2-cairo - https://www.archlinux.org/packages/extra/x86_64/python2-cairo/

**Comment by LeBaux** [comment]
Current PKGBUILD at [aur.archlinux.org/packages/pick-colour-picker](https://aur.archlinux.org/packages/pick-colour-picker) works on stock Manjaro i3 if you also install:
- python2-gobject
- python2-cairo

Maybe in the future, someone will fix the PKGBUILD. Still, best color picker on Linux, super glad it works on arch-based distros with little hustle. Cheers!

**Comment by stuartlangridge** [comment]
You can also install the snap version, which should work fine on Arch (https://docs.snapcraft.io/installing-snap-on-arch-linux) so I think it's OK to close this now.
