### ISSUE TITLE
Minimized/

### ISSUE THREAD

**Issue by pocoz** [stuartlangridge/ColourPicker#26]
Greetings! The app is excellent. But could you do so that it is minimized to tray. And picker was caused by one-click, no settings window.

**Comment by stuartlangridge** [comment]
Hi! I won't make Pick itself implement minimise-to-tray; that's not an app's job, but the job of your window manager or similar (and in Ubuntu I prefer Pick to live in the Launcher, not the notification area, and Ubuntu already does that; elementary is the same with its dock). You may want to investigate utilities like AllTray and competing projects, which I believe allow for this in other desktops?
