### ISSUE TITLE
installation on Fedora Workstation

### ISSUE THREAD

**Issue by corebots** [stuartlangridge/ColourPicker#30]
Hi, how to install your nice tool in Fedora please?

**Comment by stuartlangridge** [comment]
I'm afraid I don't know anything about distribution of apps for Fedora; if someone were to make a suggestion I might be able to make use of it, but I don't know how at the moment.

**Comment by snwh** [comment]
@stuartlangridge you could flatpak it. ;)

**Comment by corebots** [comment]
yes, flatpak would be very nice (and ease from what i read...)

**Comment by stuartlangridge** [comment]
I've looked briefly into flatpak and I don't understand how to build one for a Python app. If someone contributes a pull request I'm more than happy to make it part of the upstream build process!

**Comment by stuartlangridge** [comment]
Pick is now installed with snaps, which I believe work fine on Fedora, so that should help here.
