### ISSUE TITLE
Doesn't work in Wayland

### ISSUE THREAD

**Issue by ryanleesipes** [stuartlangridge/ColourPicker#43]
Just reporting this bug, I have no feedback other than it will only let me capture from the app itself (Pick). But even then it only gets the color black.

**Comment by stuartlangridge** [comment]
I have literally no idea how to solve this. It feels to me like this should be gtk's job. I'm happy to hear suggestions about the way to do it. Possibly Wayland just makes Pick impossible to write in the name of security.

**Comment by snwh** [comment]
You can blame Wayland, there are issues with all colour pickers under it, namely you can't use them.

**Comment by stuartlangridge** [comment]
Yup; Wayland explicitly blocks third-party apps from reading pixels they don't own. Colour picking has to be implemented by the desktop environment. So maybe Pick becomes a gnome-shell extension at some point, but that's largely a ground-up rewrite. Pick, as it currently stands, is X only.

**Comment by meson11** [comment]
Somehow, the GIMP developers manged to make their color picker working on wayland.
