### ISSUE TITLE
Does not work on 16.04

### ISSUE THREAD

**Issue by vidstige** [stuartlangridge/ColourPicker#45]
Flickers and does not pick up the colors on my Ubuntu 16.04. Can get it to work by scrolling mouse wheel frantically.

**Comment by stuartlangridge** [comment]
Yes. I have the same problem, and don't know how to fix it. Thank you for the bug; I'll try to work it out.

**Comment by GzhiYi** [comment]
Now the bug fixed ?I iinstall this  but still have the same issue.

**Comment by stuartlangridge** [comment]
I believe the latest release _may_ fix this issue. Let me know if not.
