### ISSUE TITLE
Gnome Menu Category

### ISSUE THREAD

**Issue by gitqlt** [stuartlangridge/ColourPicker#46]
Please insert  `Categories=GTK;Graphics;` into the desktop file:
`/usr/share/applications/pick-colour-picker.desktop`
(comes from pick-colour-picker_1.5-0~201702011054~ubuntu14.04.1_all.deb)

Problem:
on Gnome (MATE), Pick locates in the `Other` gorup instead of the `Graphics` group.
Thank you

**Comment by stuartlangridge** [comment]
I believe this is now fixed.
