### ISSUE TITLE
Please update for newer releases

### ISSUE THREAD

**Issue by rolandixor** [stuartlangridge/ColourPicker#48]
Pick is an indispensible tool, and it's a pity it's not as usable on newer releases of Ubuntu. Please bring it up to date if you can.

**Comment by stuartlangridge** [comment]
Can you explain what's not usable? I'm running 18.04 and it works fine there. (I only run LTSes, so I haven't tried it on the interim releases.)

**Comment by rolandixor** [comment]
The last time I used it (which was some time now, to be honest - but it would have been on either 18.04 or 18.10, since track each release), it would minimize when you click on the toolbar button to pick a new colour, but it would require you to bring the application back into focus in order to pick a new colour.

BTW, is there a snap available? I'm on 18.10, and I don't want to add a PPA for 17.10 :)

**Comment by stuartlangridge** [comment]
There isn't a snap, but I'd like there to be one; if someone were to contribute a snapcraft.yaml that would be great. I stopped working on a snap because snaps don't honour my desktop dark mode setting so it made the application look out of place.

**Comment by rolandixor** [comment]
I personally don't mind if the app looks out of place.
It's irreplacable.

**Comment by stuartlangridge** [comment]
I've now released Pick as a snap, which will run on whichever release of Ubuntu (and other OSes) you'd like, and will honour common desktop themes as well.

**Comment by rolandixor** [comment]
Thank you sir!
