### ISSUE TITLE
PPA error

### ISSUE THREAD

**Issue by rocha** [stuartlangridge/ColourPicker#49]
```
Err:31 http://ppa.launchpad.net/sil/pick/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/sil/pick/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by stuartlangridge** [comment]
Yeah, dealing with all the PPAs was annoying, so I've moved Pick to snap distribution: https://snapcraft.io/pick-colour-picker which is a lot easier for everybody, and doesn't require you to trust me with root on your machine.

**Comment by pizzadude** [comment]
@stuartlangridge thanks for snapping this! i was browsing uappexplorer and noticed it, and it came in handy when customizing a cinnamon theme! i wouldn't of ever heard of it if it weren't snapped, and unlike deepin-picker, it works on panels.
