### ISSUE TITLE
Issues with Gtk themes on Ubuntu 16.04

### ISSUE THREAD

**Issue by timsueberkrueb** [stuartlangridge/ColourPicker#5]
On Ubuntu 16.04 Unity, when using Gtk themes other than Ambiance/Radiance, I encountered issues with Pick: The window doesn't hide when it's supposed to and Compiz crashes from time to time.
I was able to reproduce this behavior with the High Contrast Theme (which is installed per default) and the [Paper Gtk Theme](https://github.com/snwh/paper-gtk-theme).

**Comment by stuartlangridge** [comment]
It looks like this is a unity bug, specifically https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1570843.

**Comment by timsueberkrueb** [comment]
@stuartlangridge the Launchpad bug was fixed in unity package (`7.4.0+16.04.20160526.1-0ubuntu1`) which has already been rolled out. I can confirm that this fixes the problem for me.

**Comment by stuartlangridge** [comment]
Hiding now works a different way, so this should hopefully be fixed.
