### ISSUE TITLE
Use the `pick` snap namespace instead

### ISSUE THREAD

**Issue by brlin-tw** [stuartlangridge/ColourPicker#53]
The `pick` snap name is *reserved* but not *registered*, as long as it doesn't conflict with other well-known application you should consider claiming it.

```
$ snapcraft register pick

We always want to ensure that users get the software they expect
for a particular name.

If needed, we will rename snaps to ensure that a particular name
reflects the software most widely expected by our community.

For example, most people would expect ‘thunderbird’ to be published by
Mozilla. They would also expect to be able to get other snaps of
Thunderbird as 'thunderbird-$username'.

Would you say that MOST users will expect 'pick' to come from
you, and be the software you intend to publish there? [y/N]: y
Registering pick.
The name 'pick' is reserved.

If you are the publisher most users expect for 'pick' then please claim the name at 'https://dashboard.snapcraft.io/register-snap/?name=pick'

Otherwise, please register another name.
```

**Comment by stuartlangridge** [comment]
Well. It is reserved, I assume, because there's already an Ubuntu package called `pick`. Would most people expect `pick` to be my app rather than that other one, a "utility to choose one option from a set of choices"? I don't know. Can I have _both_ names, pick and pick-colour-picker? I'd be happy to use `pick` as an alternative name for my snap (it seems more obvious), but I don't know who makes the decision about which app is more popular when they both have the same name.

**Comment by brlin-tw** [comment]
> I assume, because there's already an Ubuntu package called `pick`.

Likely so.

> Would most people expect pick to be my app rather than that other one, a "utility to choose one option from a set of choices"?

As the name "Pick" is a very generic term I don't think such confusion would be a problem.

> Can I have both names, pick and pick-colour-picker?

Technically yes but that's quite impractical as you have to maintain both snaps at the same time.  Normally we would migrate to the preferred name and (properly) obsolete the old one.

> I don't know who makes the decision about which app is more popular when they both have the same name

The staffs of the Snap Store will make the decision, I believe such case will only happen when:

* The other application is well-recognized and the snap will surely causes confusion
* Both application authors have the intention of distributing the snap.

**Comment by stuartlangridge** [comment]
Sadly, publishing my snap under a new name means that I lose all the existing users. I really don't want to do that. If there's a way of renaming the snap to `pick` while keeping the existing users and seamlessly migrating them to the new name, I'd be happy to, but I don't want to lose them.

**Comment by brlin-tw** [comment]
Currently there's no way to rename a snap.  You can always present a friendly notice to inform the users about the migration and make the old snap unlisted in the store, which should help saving most of them.

**Comment by stuartlangridge** [comment]
Sure, I could do that. But the only benefit I get from that is that the snap is called "pick". That doesn't seem worth it to me; anyone searching for "pick" will find it anyway, as a substring, and Pick has its own website which links to the correct page in the snap store. Once snap renaming is implemented I'll be happy to do this, but just getting a fractionally nicer (and less descriptive!) name is not worth giving everyone the rather terrible user experience of breaking an app they've installed.
