### ISSUE TITLE
Source builds and installs but doesn't run. Snap package runs but seems to be missing fonts or has unicode issues. 

### ISSUE THREAD

**Issue by adrianocr** [stuartlangridge/ColourPicker#60]
Fedora 30, all dependencies installed. No warnings or errors in output of `sudo python3 setup.py install`. 

App shows up in gnome's app list correctly. But if I try to open it, nothing ever happens. And it does seem to be running according to  

```console
➜ ps aux | grep pick
adriano  13307  0.1  0.2 432544 60080 ?        Sl   12:00   0:00 /usr/bin/python3 /usr/local/bin/pick-colour-picker
```

I tried the snap package and that one _does_ run but it seems like there's a unicode or font issue where no text displays. Screenshot: https://imgur.com/PfN85fN and https://imgur.com/Y0V1Hd7

**Comment by stuartlangridge** [comment]
I have spoken to the snapcraft people (https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora/12484) and there's been a suggestion for debugging, if you wouldn't mind. Can you run this from a Terminal window:

```
sudo /usr/libexec/snapd/snap-discard-ns pick-colour-picker
pick-colour-picker
```

and paste any output you get into the bug, so we can maybe work out what might be causing the problem?

**Comment by adrianocr** [comment]
Here's my output:

```console
in ~ 
➜ sudo /usr/libexec/snapd/snap-discard-ns pick-colour-picker
pick-colour-picker
[sudo] password for adriano: 
Gtk-Message: 20:20:14.001: Failed to load module "pk-gtk-module"
/snap/pick-colour-picker/111/lib/python3.6/site-packages/pick/__main__.py:315: Warning: Source ID 36 was not found when attempting to remove it
  GLib.source_remove(self.resize_timeout)
/snap/pick-colour-picker/111/lib/python3.6/site-packages/pick/__main__.py:315: Warning: Source ID 159 was not found when attempting to remove it
  GLib.source_remove(self.resize_timeout)
/snap/pick-colour-picker/111/lib/python3.6/site-packages/pick/__main__.py:315: Warning: Source ID 601 was not found when attempting to remove it
  GLib.source_remove(self.resize_timeout)
/snap/pick-colour-picker/111/lib/python3.6/site-packages/pick/__main__.py:315: Warning: Source ID 1238 was not found when attempting to remove it
  GLib.source_remove(self.resize_timeout)

(pick-colour-picker:23543): Gtk-CRITICAL **: 20:20:43.057: gtk_main_quit: assertion 'main_loops != NULL' failed
in ~ took 35s 
```

The 
```
/snap/pick-colour-picker/111/lib/python3.6/site-packages/pick/__main__.py:315: Warning: Source ID 36 was not found when attempting to remove it
  GLib.source_remove(self.resize_timeout)
```
 messages came when I was dragging the window around. If I don't try to move the window, those errors are not present.

**Comment by chipaca** [comment]
starting from the fedora 30 workstation iso, how do i reproduce this issue?

**Comment by chipaca** [comment]
I installed fedora 30 workstation iso to disk, booted that, `dnf install snapd`, created the `/snap` symlink, rebooted, and then ran `snap install pick-colour-picker`, and the window came up without issues.

It didn't actually _work_, because the default thing on fedora is to use wayland. Logging out and back in with the Xorg session cures it of that.

![image](https://user-images.githubusercontent.com/1543430/62041931-bc40a300-b1f4-11e9-88ff-725acf2de01b.png)

So: @adrianocr what's different in your Fedora?

**Comment by adrianocr** [comment]
From the default settings, config, etc? Nothing.

But I mean... This is my daily driver machine and I've been using it for months. I've installed several apps, libraries, scripts, etc in relation to that. Just like I'm installing color picker, I've installed other things. Maybe something is conflicting with it. But I haven't the slightest idea how I'd go about identifying that.

**Comment by chipaca** [comment]
@adrianocr what fonts are you using?

**Comment by adrianocr** [comment]
@chipaca I thought that'd might be the problem so I tried Cantarell, Ubuntu, and Roboto. The issue remains the same. I thought maybe the issue was fontconfig-infinality so I uninstalled it and rebooted. The issue remains. I reset allllllll font changes and configs via fonts tweak tool, rebooted. Issue remains.

**Comment by adrianocr** [comment]
What's interesting is if I highlight the text in the "about" info box and paste it elsewhere, the text displays correctly. Seems like Pick just isn't rendering any of my fonts. Short gif: https://cl.ly/27db77

**Comment by chipaca** [comment]
Could you run `fc-list` *inside the snap*? It's a little bit fiddly, but something like this should work:

    ~$ snap run --shell pick-colour-picker
    ~$ LD_LIBRARY_PATH=/snap/gnome-3-28-1804/current/usr/lib/x86_64-linux-gnu/ /snap/gnome-3-28-1804/current/usr/bin/fc-list

(note the second line is "inside", you can exit it to return to your usual)

**Comment by adrianocr** [comment]
Yep, here's the output of that: https://pastebin.com/A9SpPLZT

However, pick still doesn't render the fonts correctly :(

Thank you so much for being helpful by the way. Its highly appreciated.

**Comment by chipaca** [comment]
> `Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf`

I suspect that's the key of the matter.

Alas, I'm out of my depth. Maybe somebody else can pick it up from here?

**Comment by chipaca** [comment]
Actually, you said
>  I reset allllllll font changes and configs via fonts tweak tool

but, maybe the tool isn't too good at resetting things? If you don't have the `fonts.conf` you started from, I could dig it out of the iso for you, and you could try with that?

**Comment by adrianocr** [comment]
Yes please! Shoot me the original fonts.conf and I'll replace my current one with it and we'll see if that works. If not I'll head over to the ever trusty Arch wiki and see if there is any guidance on resetting a fontconfig and associated issues.

**Comment by chipaca** [comment]
https://r.chipaca.com/fonts.conf

**Comment by adrianocr** [comment]
Yup, that did it! 

![Screenshot from 2019-07-30 08-59-27](https://user-images.githubusercontent.com/7603338/62131038-60cfed00-b2a8-11e9-8323-b7055f814ba8.png)
