### ISSUE TITLE
Won't start on Ubuntu 18.04.3

### ISSUE THREAD

**Issue by o-alquimista** [stuartlangridge/ColourPicker#63]
I launch it, but nothing happens.

I'm seeing a whole lot of errors and AVC denied alerts in the attached logs. Take a look near the end of the file:
[journalctl.txt](https://github.com/stuartlangridge/ColourPicker/files/3815748/journalctl.txt)
[journalctl-pick.txt](https://github.com/stuartlangridge/ColourPicker/files/3815749/journalctl-pick.txt)

I installed it through GNOME Software, as a snap.

#### Things I've tried:
- Reboot
- `sudo snap start pick-colour-picker`, which results in: `error: snap "pick-colour-picker" has no services`, but then every snap I have installed result in this same error when trying to launch them from the terminal. They will, however, launch properly through their application launchers, except Pick.

**Comment by stuartlangridge** [comment]
You don't need to use `sudo` to launch a snap. If you just run `pick-colour-picker` in a  Terminal, is there any output?

**Comment by o-alquimista** [comment]
All right, I ran `pick-colour-picker` and there was no output. No luck.

There are AVC denied alerts. See the last lines:
[journalctl.txt](https://github.com/stuartlangridge/ColourPicker/files/3815845/journalctl.txt)


Did I break something by running it as root back there? I worry the app may have created files as root. I only ran `sudo snap start pick-colour-picker`.

**Comment by stuartlangridge** [comment]
You shouldn't have broken anything, but if you're unsure, try removing Pick from Gnome Software and then reinstalling it; that should clear anything out.

I don't understand what the AVC issue means. For ease of looking at it, here are some of the lines in question:

```
nov 06 14:10:51 alq22 audit[3781]: AVC apparmor="DENIED" operation="open" profile="snap.gnome-logs.gnome-logs" name="/var/lib/snapd/desktop/icons/" pid=3781 comm="gnome-logs" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
nov 06 14:10:51 alq22 kernel: audit: type=1400 audit(1573060251.100:48): apparmor="DENIED" operation="open" profile="snap.gnome-logs.gnome-logs" name="/var/lib/snapd/desktop/icons/" pid=3781 comm="gnome-logs" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
nov 06 14:10:56 alq22 audit[3881]: AVC apparmor="DENIED" operation="open" profile="snap.pick-colour-picker.pick-colour-picker" name="/proc/3881/mounts" pid=3881 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
nov 06 14:10:56 alq22 kernel: audit: type=1400 audit(1573060256.852:49): apparmor="DENIED" operation="open" profile="snap.pick-colour-picker.pick-colour-picker" name="/proc/3881/mounts" pid=3881 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
nov 06 14:11:01 alq22 audit[3976]: AVC apparmor="DENIED" operation="open" profile="snap.pick-colour-picker.pick-colour-picker" name="/proc/3976/mounts" pid=3976 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
nov 06 14:11:01 alq22 kernel: audit: type=1400 audit(1573060261.984:50): apparmor="DENIED" operation="open" profile="snap.pick-colour-picker.pick-colour-picker" name="/proc/3976/mounts" pid=3976 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
nov 06 14:11:05 alq22 audit[4071]: AVC apparmor="DENIED" operation="open" profile="snap.pick-colour-picker.pick-colour-picker" name="/proc/4071/mounts" pid=4071 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
nov 06 14:11:05 alq22 kernel: audit: type=1400 audit(1573060265.560:51): apparmor="DENIED" operation="open" profile="snap.pick-colour-picker.pick-colour-picker" name="/proc/4071/mounts" pid=4071 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
```

That looks like something is trying to read files in /proc and is being told it can't, which I don't think is a pick problem per se; it sounds more like a system problem with your snap setup in general. I'll ask someone more expert than me on this if they have any thoughts.

**Comment by o-alquimista** [comment]
I reinstalled Pick, but it still doesn't launch.

Now I reinstalled it using the `snap` commands:
```
snap remove pick-colour-picker
snap install pick-colour-picker
```
Same result.

I haven't installed any snap other than Pick. I haven't touched the snap component. I installed Ubuntu 18.04.3 yesterday, and the image passed signature and integrity checks. Do you really think this is something I should take to Launchpad/Ubuntu?

I've reported this here: https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1851661

The answer from an AppArmor developer:

> Hello Douglas, thanks for the report. AppArmor is one of several tools the snap packaging system uses to enforce confinement on packages. The AppArmor project doesn't supply the policy though, just the enforcement mechanism. I believe you'll need to talk to whoever wrote the snap package, as they request the privileges necessary when packaging the application.
> 
> Try 'snap info' on the name of the snap package that provides the colour picker; it should provide some contact details for the packager.
> 
> Thanks

**Comment by o-alquimista** [comment]
I have installed elementary OS, and Pick worked. I think I will try Ubuntu 18.04.3 again soon.

**Comment by o-alquimista** [comment]
Installed Ubuntu 18.04.3 again. It's working now. Closing.
