### ISSUE TITLE
please add systray icon so I can use it easily

### ISSUE THREAD

**Issue by ralyodio** [stuartlangridge/ColourPicker#71]

**Comment by stuartlangridge** [comment]
I don't really want to add a permanent indicator for Pick; it's not something that everyone likes, which means that I'd need to provide configuration to turn it on and off and Pick does its very best to not need configuration options. However, I would suggest that a reasonable workaround for this would be to install the [Script Runner indicator](https://askubuntu.com/a/786708/2387) and then add a command to it to run `pick-colour-picker --pick` which will launch Pick and immediately start picking a colour. You may also want to add a [custom keyboard shortcut](https://help.ubuntu.com/stable/ubuntu-help/keyboard-shortcuts-set.html.en) to launch that same command.
