### ISSUE TITLE
Weird behavior with Wayland + Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by stevewells20** [stuartlangridge/ColourPicker#75]
Difficult to choose which details are relevant to this issue, so I'm picking the two most likely offenders, Ubuntu 18.04 and Wayland. Pick starts correctly; when I choose the Pick a Color function, I'm asked Permission to disable shortcuts. I accept, and the Pick GUI disappears and is unrecoverable. It is still running, still listed in the app bar and in htop, but nothing I can do from then on recovers the GUI. No color chooser comes up, and nothing else happens; there are no error messages listed in terminal, and ctrl+c in terminal does not kill program. The right-click + quit option still works on the app bar.

Cheers

**Comment by stuartlangridge** [comment]
Ah. Pick is extremely unlikely to work on Wayland; the act of picking colours off the screen is done completely differently, and is considerably more difficult. Also, I don't have Wayland myself so I'm unable to test it to see what can be done. I'll try to take a look, and perhaps add a message detecting Wayland and alerting the user, but for now it's best to assume that Pick is unsupported and won't work on a Wayland desktop, I'm afraid.

**Comment by stevewells20** [comment]
After researching Wayland's security model, I came to the same conclusion. Hard to do any sort of pixel grabbing in a system designed to sandbox applications' framebuffer access to their own window. I'm going to go ahead and close this as Wayland likely can't be supported; feel free to re-open it or add additional information for people who run into the same issue.
