### ISSUE TITLE
There is no way to delete an individual history item

### ISSUE THREAD

**Issue by sgpthomas** [stuartlangridge/ColourPicker#8]
As far as I can tell, there is only a way to clear all history. I think it would be nice to delete individual history items

**Comment by stuartlangridge** [comment]
Yup. By design, because individual deletion of items would clutter the UI. I'm happy to hear suggestions for how to do this _without_ cluttering the UI if anyone has them, but in the absence of such suggestions, Pick having a simple clear UI is important and so wontfix.
