### ISSUE TITLE
Font problem

### ISSUE THREAD

**Issue by baris-inandi** [stuartlangridge/ColourPicker#81]
I am on Pop!_OS 20.04 and the app works but the font is not loaded.
Here is a screenshot:
![image](https://user-images.githubusercontent.com/68742481/122392483-935a6000-cf7c-11eb-9e1e-e976f1574593.png)

The problem might be because the font is not downloaded by default on my OS. What is the name of the font so I can download it?

Also, I suggest using a fallback font in the app like a safe font like Arial or sans-serif so that people that don't have the font installed can still use the app without this problem.

**Comment by gjwgit** [comment]
Same problem - Ubuntu 21.04 - installed using snap.

```
$ snap install pick-colour-picker

$ pick-colour-picker 

(pick-colour-picker:879908): Gtk-WARNING **: 12:32:11.056: Theme parsing error: gtk.css:1565:23: 'font-feature-settings' is not a valid property name

(pick-colour-picker:879908): Gtk-WARNING **: 12:32:11.062: Theme parsing error: gtk.css:3617:25: 'font-feature-settings' is not a valid property name

(pick-colour-picker:879908): Gtk-WARNING **: 12:32:11.063: Theme parsing error: gtk.css:4079:23: 'font-feature-settings' is not a valid property name

couldn't restore settings (error: g-io-error-quark: Error opening file /home/kayon/snap/pick-colour-picker/common/.cache/colour-picker.json: No such file or directory (1)), so assuming they're blank
```

**Comment by stuartlangridge** [comment]
Unfortunately, this appears to be a snapcraft bug rather than a Pick bug; I can't do anything to fix it, as far as I can tell. https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484 is where I informed the snap team, some time ago, but it remains unfixed and there seems to be no clear answer about how to fix it oneself.

**Comment by baris-inandi** [comment]
So we can't do anything until the snap team can fix the issue. Closing the issue.
