### ISSUE TITLE
cannot open display: :0

### ISSUE THREAD

**Issue by stuartlangridge** [stuartlangridge/ColourPicker#87]
FWIW, I tried this for the first time, on a fairly clean install of Ubuntu 22.04.1 LTS with few tweaks. NVIDIA & X Server session (default for NVIDIA GPU).

After doing `sudo snap install ... `

Tried launching , nothing happens.

So I tried in the CLI and it shows this:

```
(pick-colour-picker:14498): Gtk-WARNING **: 12:10:09.007: cannot open display: :0
```

_Originally posted by @fabd in https://github.com/stuartlangridge/ColourPicker/issues/85#issuecomment-1231459169_

**Comment by stuartlangridge** [comment]
@fabd I've moved this to a new issue.

This shouldn't happen. It looks like it can't find X running at all. Are you sure it's not running Wayland?

**Comment by fabd** [comment]
Hey I'm really sorry for wasting even a couple minutes of your day. I was indeed trying Wayland briefly as I am experimenting with using Ubuntu as my daily driver - and wasn't paying attention.

I needed a little app like ColorZilla that looks good - nice icon too. Glad it works. Cheers!

**Comment by stuartlangridge** [comment]
No problem; such things happen to us all! Pick doesn't work under Wayland, I'm afraid (and probably can't work, either; applications aren't allowed to read the screen without the connivance of the compositor, and there doesn't seem to be a standard API that compositors offer to applications to read the screen with permission).
