### ISSUE TITLE
very good app, don't abandon it!!

### ISSUE THREAD

**Issue by BarbzYHOOL** [stuartlangridge/ColourPicker#88]
very cool and useful app!

**Comment by stuartlangridge** [comment]
I'm glad you like it!

**Comment by vhbui02** [comment]
> I'm glad you like it!

I recommend you add Wayland support to this app. Modern Ubuntu version now can't run it.

**Comment by stuartlangridge** [comment]
> I recommend you add Wayland support to this app. Modern Ubuntu version now can't run it.

I am investigating adding Wayland support. It is harder than it looks, but I'll see what I can do.

**Comment by vhbui02** [comment]
> I am investigating adding Wayland support. It is harder than it looks, but I'll see what I can do.

Thank you kind sir. I really like this tool for its simplicity. Hope I could grasp some more Linux knowledge over the next few years so I can contribute to apps like yours.
