### ISSUE TITLE
Doesn't start on Xubuntu/XFCE

### ISSUE THREAD

**Issue by dflock** [stuartlangridge/ColourPicker#9]
At least, that looks like it might be the problem. This is what happens when I run it at the command line:

``` console
$ pick-colour-picker 
ERROR:root:Could not find any typelib for Unity
```

I'm running Xubuntu 13.10 (I know) and successfully installed pick using the trusty deb file, via the PPA. I'm using XFCE as a desktop env. and don't have unity installed.

**Comment by stuartlangridge** [comment]
Hrm. I deliberately surround the Unity import with a try/except; it's OK if it fails (and then we don't show the menu). So... this isn't supposed to happen. I'm not sure how I can best attempt to resolve this without having a 13.10 Xubuntu installation around, though :( If you have suggestions, or are a Python coder yourself, I'd be happy to hear about it.

**Comment by dflock** [comment]
I just tried it on Xubuntu 14.04 (on a different machine) and it works fine
- no unity there either. So I guess your unity check is working on 14.04
  but maybe doesn't work somehow on 13.10 - or on that 13.10 machine, at
  least.

If I get chance, I'll have a look at the code next week.

**Comment by flexiondotorg** [comment]
@stuartlangridge Fixed via https://github.com/stuartlangridge/ColourPicker/pull/56/commits/fa3f33dff2887cbfd3ba97dd720353725bc8a132
