### ISSUE TITLE
Pick not working in Ubuntu 22.04

### ISSUE THREAD

**Issue by vhbui02** [stuartlangridge/ColourPicker#92]
Hi, I'm trying to find Microsoft PowerToys Color Picker alternatives on Ubuntu 22.04. So far so good I've stumbled on your app, but:
- It can't pick anything beside a #000000 color
- The cursor disappeared and reappeared.

**Comment by CryptoSoo** [comment]
> Hi, I'm trying to find Microsoft PowerToys Color Picker alternatives on Ubuntu 22.04. So far so good I've stumbled on your app, but:
> 
> * It can't pick anything beside a #000000 color
> * The cursor disappeared and reappeared.

facing the same issue now, only worked for me once.

**Comment by vhbui02** [comment]
@CryptoSoo I think i know what is going on. It might be the difference in protocol settings, Ubuntu 2204 use Wayland instead of X11/Xorg as default. A lot of perennial applications were developed using X11 so they won't work on Wayland.  Anyway this is just an assumption since the devs didn't tell us they implemented Wayland support or not.

**Comment by CryptoSoo** [comment]
> 

Thank you it was the protocol settings

**Comment by vhbui02** [comment]
@CryptoSoo Case closed then :") I've never thought that I could solved a Linux-specific problem like this till now.

**Comment by stuartlangridge** [comment]
Unfortunately, Pick doesn't currently support Wayland, because doing what Pick does is a lot more difficult in a Wayland desktop. I'm investigating whether it can be done.

**Comment by nicolas-oliveira** [comment]
Is there some update from this?
